---
- name: configure developer environment
  hosts: localhost
  become: yes
  connection: local
  vars:
    home: "{{ lookup('env','HOME') }}"
    user: "{{ lookup('env','USER') }}"
  remote_user: '{{ user }}'

  tasks:
  - name: install rpmfusion
    dnf: pkg={{ item }} state=present
    when: ansible_distribution == "Fedora"
    with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm

  - name: update dnf
    dnf: pkg=* state=latest
    when: ansible_distribution == "Fedora"

  - name: install packages
    dnf: pkg={{item}} state=latest
    when: ansible_distribution == "Fedora"
    with_items:
    - autoconf
    - automake
    - clang-analyzer
    - clang-tools-extra
    - ctags
    - coccinelle
    - curl
    - exfat-utils
    - flatpak
    - fuse-exfat
    - git
    - git-email
    - gcc
    - gdb
    - golang
    - htop
    - libvirt-devel
    - make
    - meson
    - mutt
    - ncurses-devel
    - podman
    - python-devel
    - python-pip
    - qemu
    - strace
    - tmux
    - strace
    - valgrind
    - vim
    - virt-manager
    - zsh

  - name: install pip modules
    pip: name={{ item }}
    when: ansible_distribution == "Fedora"
    with_items:
      - powerline-status
      - netifaces
      - thefuck
      - ipython

  - name: create home git directory
    file:
      state: directory
      path: '{{ home }}/{{ item }}'
      owner: '{{ user }}'
      group: '{{ user }}'
    with_items:
      - git
      - .vim
      - .config/powerline/themes/tmux
      - .config/powerline/themes/vim

  - name: clone config_files repository
    git:
      repo: 'https://github.com/marcosps/config_files'
      dest: '{{ home }}/git/config_files'

  - name: install config_file files
    file:
      src: '{{ home }}/git/config_files/configs/{{ item.src }}'
      dest: '{{ home }}/{{ item.dest }}'
      state: link
      force: yes
      owner: '{{ user }}'
      group: '{{ user }}'
    with_items:
      - { src: 'gitconfig', dest: '.gitconfig' }
      - { src: 'muttrc', dest: '.muttrc' }
      - { src: 'tmux.conf', dest: '.tmux.conf' }
      - { src: 'vimrc', dest: '.vim/vimrc' }
      - { src: 'zshrc', dest: '.zshrc' }
      - { src: 'tmux_default.json', dest: '.config/powerline/themes/tmux/default.json' }
      - { src: 'vim_default.json', dest: '.config/powerline/themes/vim/default.json' }
