call plug#begin('~/.vim/plugged')
Plug 'mhinz/vim-signify'
Plug 'vim-airline/vim-airline'
Plug 'tpope/vim-fugitive'
Plug 'scrooloose/nerdcommenter'
Plug 'farmergreg/vim-lastplace'
Plug 'vim-utils/vim-man'
Plug 'rykka/riv.vim'
Plug 'stfl/meson.vim'
Plug 'lzap/vim-selinux'
Plug 'vim-airline/vim-airline-themes'
Plug 'fatih/vim-go'
Plug 'kien/ctrlp.vim'
Plug 'AndrewRadev/linediff.vim'
Plug 'pearofducks/ansible-vim'
Plug 'krisajenkins/vim-projectlocal'
Plug 'majutsushi/tagbar'
Plug 'saltstack/salt-vim'
Plug 'kaicataldo/material.vim'
call plug#end()

" disable arrow keys
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

" Map new Escape Key
imap jk <Esc>

" map toggle commenters
nmap // <leader>ci
vmap // <leader>ci

" "easify" tab keys
nmap tn :tabnext<CR>
nmap tp :tabprev<CR>

" hide hightlight from last search
nmap <silent> ./ :nohlsearch<CR>

" hide/show tagbar
nmap <F8> :TagbarToggle<CR>

syntax enable
filetype plugin on
filetype indent on

set ignorecase
set number
set smartindent
set spell spelllang=en
set nobackup
set noswapfile
set wildmenu
set wildignore=*.o,*~,*.pyc
set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store
set incsearch
set lazyredraw " do not redraw when executing macros
set ffs=unix,dos,mac " use UNIX standard file type
set path+=**
set cursorline
set cursorcolumn
set tabstop=8 shiftwidth=8 softtabstop=0
set noexpandtab
set hlsearch
set nowrap
set laststatus=2 " airline setup
set backspace=eol,start,indent " Fix mac osx delete button..
set encoding=utf-8
set textwidth=80
set history=500
set pastetoggle=<f5>
set autoread " reload file when changed from the outside
set noshowmode " don't show mode in default statusbar
"TODO: use vi powerline from powerline when it can show file diffs into
"statusbar
"set rtp+=/usr/lib/python2.7/site-packages/powerline/bindings/vim

" set folding options
set foldmethod=syntax
set foldlevelstart=1
set foldnestmax=2

set invlist " show invisible characters
set listchars=tab:▸\ ,eol:¬,trail:⋅,extends:❯,precedes:❮

set termguicolors

let javaScript_fold=1
let sh_fold_enabled=1
let c_fold_enabled=1

" Plugins setup
let g:signify_vcs_list = [ 'git', 'hg', 'svn' ]
let g:airline_theme = "material"
let g:airline_powerline_fonts=1
let g:airline#extensions#tagbar#flags = 'f'
" this algorithm works well for /** */ style comments in a tab-indented file
let g:airline#extensions#whitespace#mixed_indent_algo = 1
let b:airline_whitespace_checks = [ 'trailing', 'long' ]

" settings of syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

set background=dark
colorscheme material
